### ISSUE TITLE
on first run I just get full screen error dialog and clicking ok does nothing

### ISSUE THREAD

**Issue by maxandersen** [rvansa/ocpp#1]
whats in the error dialog
```
┌──Error──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [null]  │
│at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)                        │
│at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)                        │
│at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:155)                                     │
│at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:608)                                                  │
│at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)                                                   │
│at io.openshift.ocpp.Pods.fetchRows(Pods.java:34)                                                                                    │
│at io.openshift.ocpp.Main.fetchAndUpdate(Main.java:207)                                                                              │
│at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)                                                 │
│at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)                                                        │
│at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)          │
│at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)                                         │
│at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                                         │
│at java.base/java.lang.Thread.run(Thread.java:834)                                                                                   │
│Caused by: java.net.UnknownHostException: kubernetes.default.svc: nodename nor servname provided, or not known                       │
│at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)                                                              │
│at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)                                        │
│at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)                                                 │
│at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)                                                     │
│at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)                                                               │
│at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)                                                                │
│at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)                                                                │
│at okhttp3.Dns$1.lookup(Dns.java:40)                                                                                                 │
│at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)                                      │
│at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)                                                       │
│at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)                                                             │
│at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)                                            │
│at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)                                     │
│at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)                                                 │
│at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)                                              │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                                 │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)                                                 │
│at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)                                                       │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                                 │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)                                                 │
│at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)                                                      │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                                 │
│at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)                                 │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                                 │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)                                                 │
│at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:134)        │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                                 │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)                                                 │
│at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)                             │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                                 │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)                                                 │
│at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:69)                       │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                                 │
│at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)                                                 │
│at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)                                                               │
│at okhttp3.RealCall.execute(RealCall.java:93)                                                                                        │
│at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:469)                                  │
│at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)                                  │
│at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)                                  │
│at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151)                                     │
│... 10 more                                                                                                                          │
│
```

**Comment by rvansa** [comment]
Thanks for the report, it seems that not having `~/.kube/config` set leads to an unhandled error. Working on a fix.

**Comment by rvansa** [comment]
@maxandersen I've pushed the fix, it should ask you for login credentials and persist them in kubeconfig.
